Front/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from home.views import hello
from django.conf import settings
from django.conf.urls.static import static

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="main"),
    path('users/', include('users.urls')),
    path('hello',hello, name="hello"),
    path('board/', include('home.urls'), name='home'),
    path('signup/', include('signup.urls')),
    path('upload/', upload, name='upload'),
    path('result/', include('result.urls'), name="result"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Front/bigproject/home/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "home" # 앱 이름 설정
urlpatterns = [
    path('go_hello/', hello, name="hello"),
    path('', question_list, name="question_list"),
    path('<int:question_id>/', question_detail, name="question_detail"),
    path('answer/create/<int:question_id>/', answer_create, name="answer_create"),
    path('question_create/', question_create, name="question_create"),
    path('<int:pk>/edit/', question_edit, name='question_edit'),
    path('<int:pk>/delete/', question_delete, name='question_delete'),
    path('<int:pk>/answer/delete/', answer_delete, name='answer_delete'),
    path('search/', search, name="search"),
]

Front/bigproject/result/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "result" # 앱 이름 설정
urlpatterns = [
    path('result_create', result_create, name="result"),
    path('', result_list, name="result_list"),
    path('download/', file_download, name='file_download'),
    path('<int:result_id>', result_detail, name="result_detail"),
]

Front/bigproject/result/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Result(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    create_date = models.DateTimeField(auto_now = True)
    file = models.FileField(null=True, upload_to='files')
    # 0=None
    # 1=대기중
    # 2=변환중
    # 3=변환완료
    status = models.IntegerField(default=1)
    instrument = models.IntegerField(default=1)

Front/bigproject/result/forms.py
from django import forms
from result.models import Result

class ResultForm(forms.ModelForm): # 모델 폼을 상속받은 QuestionForm 클래스
  class Meta: # 내부 Meta 클래스
    model = Result
    fields = ['file']
    # labels 코드 추가하기
    labels = {
      'file' : '첨부파일',
    }
    

Front/bigproject/result/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.core.paginator import Paginator
from django.contrib import messages
from datetime import datetime
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import os
import numpy as np

# Create your views here.
def result_create(request):
  if request.user.is_anonymous:
    return redirect('users:login')
  else:
    if request.method == 'POST':
      files = request.FILES.get('file')
      result = Result()
      result.create_date = datetime.now()
      result.user = request.user
      result.file = request.FILES.get('file')
      file_path = os.path.join(settings.MEDIA_ROOT, str(files))
      print(file_path)
      result.save()
      #subprocess.Popen(["python", "subprocess.py", str(files)])
        
      # separator = Separator('spleeter:2stems')
      # audio_loader = AudioAdapter.default()
      # waveform, _ = audio_loader.load(result.file.path, sample_rate=44100)
      # prediction = separator.separate(waveform)

        # path_music = 'media/'
        # os.makedirs(path_music, exist_ok=True)
        # media 폴더 -> 각 아아디 마다 폴더 -> 내가 선택한 음익 -> 분류된 음악
        # meida/ID/Music/Music_drum.mp3, Music_bass.mp3, Music.bass.mp3… 이런식으로? 

      # for inst in list(prediction.keys()):
      #   channels = 2 if (prediction[inst].ndim == 2 and prediction[inst].shape[1] == 2) else 1
      #   y = np.int16(prediction[inst] * 2 ** 15)

      #   song = pydub.AudioSegment(y.tobytes(), frame_rate=44100, sample_width=2, channels=channels)
      #   song.export('media/' + f"{name}_{inst}.mp3", format="mp3", bitrate="320k")
      
      #context = {'result': result}
      return redirect('result:result_list')
    else:
      return redirect('main')
  
def result_list(request):
  if request.user.is_anonymous:
    return redirect('users:login')
  else:
    result = Result.objects.all().order_by('-create_date') # Question 모델 데이터를 작성일시의 역순(-)으로 정렬한다.
    # Paging 기능 구현하기
    result_list = result.filter(user__username=request.user)
    page = request.GET.get('page', '1') # GET 방식 요청 URL에서 page값을 가져올 때 사용(?page=1). page 파라미터가 없는 URL을 위해 기본값으로 1을 지정한 것
    paginator = Paginator(result_list, 5) # Paginator 클래스는 questions를 페이징 객체 paginator로 변환. 페이지당 5개씩 보여주기
    page_obj = paginator.get_page(page) # page_obj 객체에는 여러 속성이 존재
    context = { 'result' : page_obj } # page_obj를 question_list에 저장한다.
    return render(request, 'result/result_list.html', context)

def file_download(request):
    path = request.GET['path']
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    print(path)
    print(file_path)
    if os.path.exists(file_path):
        binary_file = open(file_path, 'rb')
        response = HttpResponse(binary_file.read(), content_type="application/octet-stream; charset=utf-8")
        response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
        return response
    else:
        message = '알 수 없는 오류가 발생하였습니다.'
        return HttpResponse("<script>alert('"+ message +"');history.back()'</script>")
      
def result_detail(request, result_id):
  result = get_object_or_404(Result, pk=result_id)
  
  context = { 'result' : result }
  returns = []
  
  for i in range(1, 16):
    path = 'media/' + result.file.name + '-' + str(i) + '.png'
    print(path)
    if os.path.exists(path):
      returns.append("../" + path)
      
  context['ret'] = returns
  context['mid'] = str(result.file.name) + '.mid'
  context['mp3'] = str(result.file.name)
  
  return render(request, 'result/result.html', context)

Front/bigproject/result/templates/result/result.html
{% extends 'base.html' %}
{% load home_filter %}
{% block content %}
<div class="container">
    <main class="mb-auto col-12">
        <br /><br /><br />
        <audio controls>
            <source src='/media/{{ mp3 }}'>
        </audio>
        <h1><a href='/media/{{ mid }}'>download .mid</a></h1>
    </main>
    {% for r in ret %}
    <img src="{{ r }}" width='80%' /><br />
    {% endfor %}
</div>

{% endblock %}

Front/bigproject/result/templates/result/result_list.html
{% extends 'base.html' %}
{% load home_filter %}
{% block content %}

  <div class="container">  
    <table class="board-list">
      <thead>
        <tr class="thead-white">
          <th scope="col" class="th-title" height="70">작성자</th>
          <th scope="col" class="th-date" height="70">작성일시</th>
          <th scope="col" class="th-title" height="70">파일명</th>
          <th scope="col" class="th-title" height="70">악기</th>
        </tr>
      </thead>
      <tbody>
        {% if result %}
        {% for results in result %}
        {% if results.user == request.user %}
        <tr>
          <td height="70">{{ results.user }}</td>
          <td>
            {{ results.create_date }}
          </td>
          {% comment %} <td><a href="/result/download/?path=/{{ results.file }}">{{ results.file }}</a></td> {% endcomment %}
          <td>
          {% if results.status == 1 %}
          <p style='color:#555555'>기다리는 중...</p>
          {% elif results.status == 2 %}
          <p style='color:#ff781f'>처리 중...</p>
          {% elif results.status == 3 %}
          <a href="{% url 'result:result_detail' results.id %}">{{ results.file }}</a>
          {% elif results.status == 4 %}
          <p style='color:#b22222'>파일 형식이 알맞지 않습니다.</p>
          {% endif %}
          </td>
          <td>
            {% if results.instrument == 1 %}
            Piano
            {% elif results.instrument == 2 %}
            Guitar
            {% elif results.instrument == 3 %}
            Violin
            {% endif %}
          </td>
        </tr>
        {% endif %}
        {% endfor %}
        {% else %}
        <tr>
          <td colspan="3">글이 없습니다.</td>
        </tr>
        {% endif %}
      </tbody>
    </table>     
  </div>   
  <ul>
    <li>
      <div style="text-align:center">
    <!-- 이전 페이지가 있으면 -->
      {% if result.has_previous %}
      <a href="?page={{ start_index }}" style="color:black" class="btn btn-outline-danger">맨앞</a>
      <a href="?page={{ result.previous_page_number }}" style="color:black" class="btn btn-outline-warning">이전</a>
      {% endif %}
      <!-- 페이지 리스트 -->
      {% for page_number in result.paginator.page_range %}
      <!-- 코드 추가하기 : 페이지 표시 제한 기능 구현하기 -->
      {% if result.number|add:3 >= page_number and page_number >= result.number|add:-3 %}
      <!-- 현재 페이지 번호랑 같다면 style을 다르게 줄 수 있다. -->
      {% if page_number == result.number %}
      <a href="?page={{ page_number }}" style="color:blue" class="btn btn-outline-dark">{{ page_number }}</a>
      {% else %}
      <a href="?page={{ page_number }}" style="color:black" class="btn btn-outline-warning">{{ page_number }}</a>
      {% endif %}
      {% endif %}
      {% endfor%}
      <!-- 다음 페이지가 있으면 -->
      {% if result.has_next %}
      <a href="?page={{ result.next_page_number }}" style="color:black" class="btn btn-outline-warning">다음</a>
      <a href="?page={{ result.end_index }}" style="color:black" class="btn btn-outline-danger">맨뒤</a>
      {% endif %}
      </div>
    </li>
  </ul>

{% endblock %}