Front/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from home.views import hello
from django.conf import settings
from django.conf.urls.static import static

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="main"),
    path('users/', include('users.urls')),
    path('hello',hello, name="hello"),
    path('board/', include('home.urls'), name='home'),
    path('signup/', include('signup.urls')),
    path('upload/', upload, name='upload'),
    path('result/', include('result.urls'), name="result"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Front/bigproject/home/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "home" # 앱 이름 설정
urlpatterns = [
    path('go_hello/', hello, name="hello"),
    path('', question_list, name="question_list"),
    path('<int:question_id>/', question_detail, name="question_detail"),
    path('answer/create/<int:question_id>/', answer_create, name="answer_create"),
    path('question_create/', question_create, name="question_create"),
    path('<int:pk>/edit/', question_edit, name='question_edit'),
    path('<int:pk>/delete/', question_delete, name='question_delete'),
    path('<int:pk>/answer/delete/', answer_delete, name='answer_delete'),
    path('search/', search, name="search"),
]

Front/bigproject/result/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "result" # 앱 이름 설정
urlpatterns = [
    path('result_create', result_create, name="result"),
    path('', result_list, name="result_list"),
    path('download/', file_download, name='file_download'),
    path('<int:result_id>', result_detail, name="result_detail"),
]

Front/bigproject/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import *
from .models import *


app_name = 'users'
urlpatterns = [
    path('login/', signup, name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', mypage, name='mypage'),
    path('update/', update, name='update'),
    path('delete', delete, name='delete'),
    # path('password/', password, name='password'),
    path('update/', update, name='update'),
    path('password/', password, name='change_password')
]

Front/bigproject/bigproject/forms.py
from django import forms
from signup.models import User
        
class PostForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['upload']

Front/bigproject/bigproject/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from home.models import *
from .forms import PostForm
from signup.models import *
from result.models import *


def main(request):
  return render(request, 'main.html')

def index(request):
    return render(request, 'index.html')
  

def upload1(request):
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES) # NOTE: 인자 순서주의 POST, FILES
		#modelform = PostForm(request.POST)
		if form.is_valid():
			form = form.save(commit=False)
			form.music = request.FILES.get('music',None)
			form.save()
			return redirect('upload')
	else:
		form = PostForm()
	return render(request, 'upload.html',{
		'form': form,
	})

def musicfile(request):
	if request.method == 'GET':
		modelform = PostForm()
		return render(request, 'upload.html', {'modelform': modelform})
	elif request.method == 'POST':
		modelform = PostForm(request.POST)
		if modelform.is_valid():
			post = modelform.save(commit=False)
			post.music = request.FILES.get('music',None)
			post.save()
			return redirect('upload')

def upload(request):
    if request.method == 'POST' and request.FILES['file']:
        file  = request.FILES.get('file')
        
        
        
        

Front/bigproject/bigproject/templates/index.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="static/img/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="static/img/favicon.png">
    <meta name="author" content="Holger Koenemann">
    <meta name="generator" content="Eleventy v2.0.0">
    <meta name="HandheldFriendly" content="true">
    <title>BTS</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script>
      function chkSubmit(e){
        if(document.getElementById('file').value == ''){
          alert('파일을 선택해주세요.')
          return false;
        } else{
          return true;
        }
      }
    </script>
    <style>
      .hide{
        width:0px;
        height:0px;
        opacity:0px;
      }
      .instrument_radio + img{
        border:12px solid #555555;
      }
      .instrument_radio:checked + img{
        border-color:#FF0000;
      }
      /* inter-300 - latin */
      @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 300;
      font-display: swap;
      src: local(''),
      url('static/fonts/inter-v12-latin-300.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('static/fonts/inter-v12-latin-300.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }
      /* inter-400 - latin */
      @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: local(''),
      url('static/fonts/inter-v12-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('static/fonts/inter-v12-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }
      @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 500;
      font-display: swap;
      src: local(''),
      url('static/fonts/inter-v12-latin-500.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('static/fonts/inter-v12-latin-500.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }
      @font-face {
      font-family: 'Inter';
      font-style: normal;
      font-weight: 700;
      font-display: swap;
      src: local(''),
      url('static/fonts/inter-v12-latin-700.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
      url('static/fonts/inter-v12-latin-700.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }
      .abcde {
          margin: 0 auto;
          padding: 0;
          width: 1500px;
          height: 800px;
          background: radial-gradient(#ffcc99,#9999ff);

      }
    </style>
  </head>
  <body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">
    <nav id="navScroll" class="navbar navbar-dark bg-black fixed-top px-vw-5" tabindex="0">
      <div class="container">
        <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href="">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
            <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
            <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"/>
          </svg>
          <span class="ms-md-1 mt-1 fw-bolder me-md-5"><strong>BTS</strong></span>
        </a>
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 list-group list-group-horizontal">
          <li class="nav-item">
            <a class="nav-link fs-5" href="" aria-label="Homepage">
            Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5" href="{% url 'home:question_list' %}" aria-label="A sample content page">
            게시판
            </a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link fs-5" href="{% url 'users:mypage' %}" aria-label="A system message page">마이페이지</a>
            {% endif %}
          </li>
        </ul>
        {% if user.is_authenticated %}
        <a href="{% url 'users:logout' %}" aria-label="Download this template" class="btn btn-outline-light">
        <small> {{ user.username }}님 로그아웃 </small>
        </a>
        {% else %}
        <a href="/users/login" aria-label="Download this template" class="btn btn-outline-light">
        <small> Login </small>
        </a>
        {% endif %}
      </div>
    </nav>
    <main>
    <div class="w-100 overflow-hidden position-relative bg-black text-white" data-aos="fade">
      <div class="abcde">
      <div class="container py-vh-4 position-relative mt-5 px-vw-5 text-center">
        <div class="row d-flex align-items-center justify-content-center py-vh-5">
          <div class="col-12 col-xl-10">
            <h1 class="display-huge mt-3 mb-3 lh-1"> <b>Beat To Sheet</b></h1>
          </div>
          <div class="col-12 col-xl-8">
            <p class="lead text-secondary"><b>누구나 원하는 음악을 악보로 변환</b></p>
          </div>
          <form method="POST" action="{% url 'result:result' %}" enctype="multipart/form-data" onsubmit='return chkSubmit(this)'>
            {% csrf_token %}
            <div class="col-12 text-center">
              <div class="form-group">
                <fieldset>
                  <label for="content"></label>
                  <input type="file" id="file" name="file" class="btn btn-outline-dark" accept="audio/*">
                </fieldset>
              </div>
              <br />
              <label><input type='radio' name='instrument' class='hide instrument_radio' id='radio_piano' checked='checked' /><img src="static/img/pianoIcon.png" style='padding:18px;cursor:pointer;' height="200" class="position-relative rounded-5 shadow" data-aos="fade-up"></label>&nbsp;&nbsp;
              <label><input type='radio' name='instrument' class='hide instrument_radio' id='radio_guitar' /><img src="static/img/guitarIcon.png" style='padding:18px;cursor:pointer;' height="200" class="position-relative rounded-5 shadow" data-aos="fade-up"></label>&nbsp;&nbsp;
              <label><input type='radio' name='instrument' class='hide instrument_radio' id='radio_violin' /><img src="static/img/violinIcon.png" style='padding:18px;cursor:pointer;' height="200" class="position-relative rounded-5 shadow" data-aos="fade-up"></label>
              <br />
              <br />
              <button type="submit" class="btn btn-xl btn-light">음악 업로드</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

    <script src="../../static/js/bootstrap.bundle.min.js"></script>
    <script src="../../static/js/aos.js"></script>
    <script>
      AOS.init({
       duration: 800, // values from 0 to 3000, with step 50ms
      });
    </script>
    <script>
      let scrollpos = window.scrollY
      const header = document.querySelector(".navbar")
      const header_height = header.offsetHeight
      
      const add_class_on_scroll = () => header.classList.add("scrolled", "shadow-sm")
      const remove_class_on_scroll = () => header.classList.remove("scrolled", "shadow-sm")
      
      window.addEventListener('scroll', function() {
        scrollpos = window.scrollY;
      
        if (scrollpos >= header_height) { add_class_on_scroll() }
        else { remove_class_on_scroll() }
      })
    </script>
  </body>
</html>

Front/bigproject/bigproject/templates/index_.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">

  <head>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
  <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="static/img/favicon-16x16.png">
  <link rel="icon" type="image/png" sizes="96x96" href="static/img/favicon.png">
  <meta name="author" content="Holger Koenemann">
  <meta name="generator" content="Eleventy v2.0.0">
  <meta name="HandheldFriendly" content="true">
  <title>BTS</title>
  <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">
  <script src="{% static 'js/bootstrap.min.js' %}"></script>

   <style>

/* inter-300 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 300;
  font-display: swap;
  src: local(''),
       url('static/fonts/inter-v12-latin-300.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('static/fonts/inter-v12-latin-300.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

/* inter-400 - latin */
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: local(''),
       url('static/fonts/inter-v12-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('static/fonts/inter-v12-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: local(''),
       url('static/fonts/inter-v12-latin-500.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('static/fonts/inter-v12-latin-500.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: local(''),
       url('static/fonts/inter-v12-latin-700.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('static/fonts/inter-v12-latin-700.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

</style>


  </head>

  <body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">

    <nav id="navScroll" class="navbar navbar-dark bg-black fixed-top px-vw-5" tabindex="0">
  <div class="container">
    <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href="">
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
    <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
    <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"/>
  </svg>
  <span class="ms-md-1 mt-1 fw-bolder me-md-5"><strong>BTS</strong></span>
</a>

      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 list-group list-group-horizontal">
      <li class="nav-item">
  <a class="nav-link fs-5" href="" aria-label="Homepage">
    Home
  </a>
</li>
<li class="nav-item">
  <a class="nav-link fs-5" href="{% url 'home:question_list' %}" aria-label="A sample content page">
    게시판
  </a>
</li>
<li class="nav-item">
  {% if user.is_authenticated %}
  <a class="nav-link fs-5" href="{% url 'users:mypage' %}" aria-label="A system message page">마이페이지</a>
  {% endif %}
</li>

    </ul>
      {% if user.is_authenticated %}
      <a href="{% url 'users:logout' %}" aria-label="Download this template" class="btn btn-outline-light">
        <small> {{ user.username }}님 로그아웃 </small>
      </a>
      {% else %}
      <a href="/users/login" aria-label="Download this template" class="btn btn-outline-light">
        <small> Login </small>
      </a>
      {% endif %}
</div>
</nav>

    <main>
      <div class="w-100 overflow-hidden position-relative bg-black text-white" data-aos="fade">
  <div class="position-absolute w-100 h-100 bg-black opacity-75 top-0 start-0"></div>
  <div class="container py-vh-4 position-relative mt-5 px-vw-5 text-center">
  <div class="row d-flex align-items-center justify-content-center py-vh-5">
    <div class="col-12 col-xl-10">
      <span class="h5 text-secondary fw-lighter">Our Mission</span>
      <h1 class="display-huge mt-3 mb-3 lh-1"> Beat To Sheet</h1>
    </div>
    <div class="col-12 col-xl-8">
      <p class="lead text-secondary">원하는 음악을 악보로!!</p>
    </div>
    <form method="POST" action="{% url 'result:result' %}" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="col-12 text-center">
        <div class="form-group">
          <fieldset>
          <label for="content">파일 첨부</label>
          <input type="file" id="file" name="file" class="btn btn-outline-dark">
          </fieldset>
        </div>
        <br>
        <button type="submit" class="btn btn-xl btn-light">저장하기</button>
      </div>
    </form>
  </div>
</div>

</div>

<div class="w-100 position-relative bg-black text-white bg-cover d-flex align-items-center">
  <div class="container-fluid px-vw-5">
    <div class="position-absolute w-100 h-50 bg-dark bottom-0 start-0"></div>
    <div class="row d-flex align-items-center position-relative justify-content-center px-0 g-5">
      <div class="col-12 col-lg-6">
        <a href="'http://naver.com"></a>
          <img src="https://kr.yamaha.com/ko/files/header_video_mobile_image_2_910bef7cf0bd338fbed3f61e1519f280.jpg" width="2280" height="1732" alt="abstract image" class="img-fluid position-relative rounded-5 shadow" data-aos="fade-up">
        </a>
      </div>
      <div class="col-12 col-md-6 col-lg-3">
        <img src="static/img/webp/abstract6.webp" width="1116" height="1578" alt="abstract image" class="img-fluid position-relative rounded-5 shadow" data-aos="fade-up" data-aos-duration="2000">
      </div>
      <div class="col-12 col-md-6 col-lg-3">
        <img src="static/img/webp/abstract9.webp" width="1116" height="848" alt="abstract image" class="img-fluid position-relative rounded-5 shadow" data-aos="fade-up" data-aos-duration="3000">
      </div>
    </div>
  </div>
</div>
<div class="bg-dark">
  <div class="container px-vw-5 py-vh-5">
    <div class="row d-flex align-items-center">
      <div class="col-12 col-lg-7 text-lg-end" data-aos="fade-right">
        <span class="h5 text-secondary fw-lighter">What we do</span>
        <h2 class="display-4">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</h2>
      </div>
      <div class="col-12 col-lg-5" data-aos="fade-left">
        <h3 class="pt-5">Product Design & Strategy</h3>
        <p class="text-secondary">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.<br>
          <a href="#" class="link-fancy link-fancy-light me-2">Tell me more</a>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
</svg>
</p>
        <h3 class="border-top border-secondary pt-5 mt-5">Development & Engineering</h3>
        <p class="text-secondary">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.<br>
          <a href="#" class="link-fancy link-fancy-light me-2">Tell me more</a>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-arrow-right-circle" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
</svg>
</p>
      </div>
    </div>
  </div>
</div>





<script src="static/js/bootstrap.bundle.min.js"></script>
<script src="static/js/aos.js"></script>
<script>
AOS.init({
 duration: 800, // values from 0 to 3000, with step 50ms
});
</script>
<script>
  let scrollpos = window.scrollY
  const header = document.querySelector(".navbar")
  const header_height = header.offsetHeight

  const add_class_on_scroll = () => header.classList.add("scrolled", "shadow-sm")
  const remove_class_on_scroll = () => header.classList.remove("scrolled", "shadow-sm")

  window.addEventListener('scroll', function() {
    scrollpos = window.scrollY;

    if (scrollpos >= header_height) { add_class_on_scroll() }
    else { remove_class_on_scroll() }

    console.log(scrollpos)
  })
</script>

  </body>
</html>

Front/bigproject/bigproject/templates/main.html
{% extends 'base.html' %}
{% block content %}

<h1>main 창</h1>
<a href="/home/go_hello">누르면 이동해요</a>
<br>
<a href="/home">질문리스트</a>

{% endblock %}

Front/bigproject/bigproject/templates/system.html
<!doctype html>
<html class="h-100" lang="en">

  <head>
      <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
  <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
  <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
  <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png">
  <meta name="author" content="Holger Koenemann">
  <meta name="generator" content="Eleventy v2.0.0">
  <meta name="HandheldFriendly" content="true">
  <title>Register a new account</title>
  <link rel="stylesheet" href="css/theme.min.css">


  </head>

  <body class="d-flex h-100 w-100 bg-black text-white" data-bs-spy="scroll" data-bs-target="#navScroll">

    <div class="h-100 container-fluid">
      <div class="h-100 row d-flex align-items-stretch">
        
          <div class="col-12 col-md-7 col-lg-6 col-xl-5 d-flex align-items-start flex-column px-vw-5">
          
            <header class="mb-auto py-vh-2 col-12">
              <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href="index.html">
  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
    <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
    <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"/>
  </svg>
  <span class="ms-md-1 mt-1 fw-bolder me-md-5">Klar</span>
</a>

            </header>
            <main class="mb-auto col-12">
              <h1>Register a new account</h1>
              
<form class="row">
  <div class="col-12">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control form-control-lg bg-gray-800 border-dark" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control form-control-lg bg-gray-800 border-dark" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check py-3">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">If you really don´t want any newsletter <strong>check this box</strong>. Then you just agree to receive our marketing mails and product stuff. If you check this box <strong>we will not send out our newsletter</strong> to you at all...on mondays.</label>
  </div>
  <button type="submit" class="btn btn-white btn-xl mb-4">Submit</button>
</div>
</form>

            </main>
          </div>
          
            <div class="col-12 col-md-5 col-lg-6 col-xl-7 gradient"></div>
          
        </div>

      </div></body>
    </html>