Front/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from home.views import hello
from django.conf import settings
from django.conf.urls.static import static

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="main"),
    path('users/', include('users.urls')),
    path('hello',hello, name="hello"),
    path('board/', include('home.urls'), name='home'),
    path('signup/', include('signup.urls')),
    path('upload/', upload, name='upload'),
    path('result/', include('result.urls'), name="result"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Front/bigproject/home/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "home" # 앱 이름 설정
urlpatterns = [
    path('go_hello/', hello, name="hello"),
    path('', question_list, name="question_list"),
    path('<int:question_id>/', question_detail, name="question_detail"),
    path('answer/create/<int:question_id>/', answer_create, name="answer_create"),
    path('question_create/', question_create, name="question_create"),
    path('<int:pk>/edit/', question_edit, name='question_edit'),
    path('<int:pk>/delete/', question_delete, name='question_delete'),
    path('<int:pk>/answer/delete/', answer_delete, name='answer_delete'),
    path('search/', search, name="search"),
]

Front/bigproject/result/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "result" # 앱 이름 설정
urlpatterns = [
    path('result_create', result_create, name="result"),
    path('', result_list, name="result_list"),
    path('download/', file_download, name='file_download'),
    path('<int:result_id>', result_detail, name="result_detail"),
]

Front/bigproject/signup/urls.py
from django.urls import path
from .views import *

app_name = 'signup'

urlpatterns = [
    path('', signup, name='signup'),
]

Front/bigproject/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import *
from .models import *


app_name = 'users'
urlpatterns = [
    path('login/', signup, name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', mypage, name='mypage'),
    path('update/', update, name='update'),
    path('delete', delete, name='delete'),
    # path('password/', password, name='password'),
    path('update/', update, name='update'),
    path('password/', password, name='change_password')
]

Front/bigproject/users/models.py
from django.db import models

# Create your models here.

Front/bigproject/users/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django import forms
# from .models import User

[]
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']

Front/bigproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import UserChangeForm
from .forms import CustomUserChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages, auth


def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main')
        else:
            error_message = 'Invalid username or password'
            return render(request, 'users/login1.html', {'error_message': error_message})

    else:
        return render(request, 'users/login1.html')


def mypage(request):
    if request.user.is_anonymous:
        return redirect("users:login")
    else:
        return render(request, 'users/profile.html')


# def update(request):
#     user_change_form = UserChangeForm(instance=request.user)
#     return render(request, 'users/profile.html', {'user_change_form': user_change_form})


def update(request):
    if request.method == 'POST':
        user_change_form = CustomUserChangeForm(
            request.POST, instance=request.user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('users:mypage')

    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
        return render(request, 'users/update.html',
                      {'user_change_form': user_change_form})


def delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('main')
    return render(request, 'users/delete.html')


# @login_required
# def password(request):
#     if request.method == 'POST':
#         password_change_form = PasswordChangeForm(request.user, request.POST)

#         if password_change_form.is_valid():
#             # 추가된 부분
#             user = password_change_form.save()
#             update_session_auth_hash(request, user)
#             # 끝
#             return redirect('main')

#     else:
#         password_change_form = PasswordChangeForm(request.user)
#     return render(request, 'users/password.html', {
#         'password_change_form': password_change_form
#     })

@login_required
def password(request):
  if request.method == "POST":
    user = request.user
    origin_password = request.POST["origin_password"]
    if check_password(origin_password, user.password):
      new_password = request.POST["new_password"]
      confirm_password = request.POST["confirm_password"]
      if new_password == confirm_password:
        user.set_password(new_password)
        user.save()
        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('users:mypage')
      else:
        messages.error(request, 'Password not same')
    else:
      messages.error(request, 'Password not correct')
    return render(request, 'change_password.html')
  else:
    return render(request, 'change_password.html')

Front/bigproject/users/templates/users/form_errors.html
{% if form.errors %} {% for field in form %} {% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div>
  <strong>{{ field.label }}</strong>
  {{ error }}
</div>
{% endfor %} {% endfor %} {% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div>
  <strong>{{ error }}</strong>
</div>
{% endfor %} {% endif %}

Front/bigproject/users/templates/users/login.html
{% extends 'base.html' %} {% block content %}

<h1>로그인</h1>

<form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}

  <div>
    <label for="username">사용자 ID</label>
    <input type="text" name="username" id="username" />
  </div>
  <div>
    <label for="password">비밀번호</label>
    <input type="password" name="password" id="password" />
  </div>
  {% if error_message %}
  <p>{{ error_message }}</p>
  {% endif %}
  <button type="submit">로그인</button><br />
  <a href="{% url 'signup:signup' %}">회원가입</a>
</form>
{% comment %}
<h1>Login</h1>

<form method="POST" action="{% url 'users:login' %}">
  {% csrf_token %} {% include 'users/form_errors.html' %}
  <label for="username">Username:</label><br />
  <input type="text" id="username" name="username" /><br />
  <label for="password">Password:</label><br />
  <input type="password" id="password" name="password" /><br /><br />
  <input type="submit" value="Login" />
</form>
{% endcomment %} {% endblock %}

Front/bigproject/users/templates/users/password.html
{% load static %}
<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,shrink-to-fit=no"
    />
    <meta
      name="description"
      content="A well made and handcrafted Bootstrap 5 template"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/favicon-16x16.png"
    />
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png" />
    <meta name="author" content="Holger Koenemann" />
    <meta name="generator" content="Eleventy v2.0.0" />
    <meta name="HandheldFriendly" content="true" />
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>

  <body
    class="d-flex h-100 w-100 bg-black text-white"
    data-bs-spy="scroll"
    data-bs-target="#navScroll"
  >
    <div class="h-100 container-fluid">
      <div class="h-100 row d-flex align-items-stretch">
        <div
          class="col-12 col-md-7 col-lg-6 col-xl-5 d-flex align-items-start flex-column px-vw-5"
        >
          <header class="mb-auto py-vh-2 col-12">
            <a
              class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center"
              href="../../"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                fill="currentColor"
                class="bi bi-stack"
                viewBox="0 0 16 16"
              >
                <path
                  d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"
                />
                <path
                  d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"
                />
              </svg>
              <span class="ms-md-1 mt-1 fw-bolder me-md-5">BTS</span>
            </a>
          </header>
          <main class="mb-auto col-12">
            <h1>Login</h1>

            <form class="row" method="post" action="{% url 'users:login' %}">
              {% csrf_token %}{{ password_change_form }}
              <div class="col-12">
              
                <button type="submit" class="btn btn-white btn-xl mb-4">
                  Submit</button
                ><br />
                <a href="{% url 'users:delete' %}" style="color:red" class="btn btn-online-danger">회원탈퇴</a>
                <a href="{% url 'users:change_password' %}" style="color:white" class="btn btn-online-danger">비밀번호 변경</a>
              </div>
            </form>
          </main>
        </div>

        <div class="col-12 col-md-5 col-lg-6 col-xl-7 gradient"></div>
      </div>
    </div>
  </body>
</html>

Front/bigproject/users/templates/users/people.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1>{{ people.username }}</h1>
  {% if user == people %}
  <div>
    <a href="{% url 'users:update' %}">계정정보수정</a>
  </div>
  {% endif %}
  <div class="row">
    {% for post in people.post_set.all %}
    <div class="col-4">
      <img src="{{ post.image_set.first.file.url }}" class="img-fluid" />
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Front/bigproject/users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,shrink-to-fit=no"
    />
    <meta
      name="description"
      content="A well made and handcrafted Bootstrap 5 template"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="../../static/img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="../../static/img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="../../static/img/favicon-16x16.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="96x96"
      href="../../static/img/favicon.png"
    />
    <meta name="author" content="Holger Koenemann" />
    <meta name="generator" content="Eleventy v2.0.0" />
    <meta name="HandheldFriendly" content="true" />
    <title>BTS</title>
    <link rel="stylesheet" href="{% static 'css/table.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <style>
      /* inter-300 - latin */
      @font-face {
        font-family: "Inter";
        font-style: normal;
        font-weight: 300;
        font-display: swap;
        src: local(""),
          url("../../static/fonts/inter-v12-latin-300.woff2") format("woff2"),
          /* Chrome 26+, Opera 23+, Firefox 39+ */
            url("../../static/fonts/inter-v12-latin-300.woff") format("woff");
        /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }

      /* inter-400 - latin */
      @font-face {
        font-family: "Inter";
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: local(""),
          url("../../static/fonts/inter-v12-latin-regular.woff2")
            format("woff2"),
          /* Chrome 26+, Opera 23+, Firefox 39+ */
            url("../../static/fonts/inter-v12-latin-regular.woff")
            format("woff");
        /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }

      @font-face {
        font-family: "Inter";
        font-style: normal;
        font-weight: 500;
        font-display: swap;
        src: local(""),
          url("../../static/fonts/inter-v12-latin-500.woff2") format("woff2"),
          /* Chrome 26+, Opera 23+, Firefox 39+ */
            url("../../static/fonts/inter-v12-latin-500.woff") format("woff");
        /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }

      @font-face {
        font-family: "Inter";
        font-style: normal;
        font-weight: 700;
        font-display: swap;
        src: local(""),
          url("../../static/fonts/inter-v12-latin-700.woff2") format("woff2"),
          /* Chrome 26+, Opera 23+, Firefox 39+ */
            url("../../static/fonts/inter-v12-latin-700.woff") format("woff");
        /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
      }
    </style>
  </head>

  <body
    class="bg-black text-white mt-0"
    data-bs-spy="scroll"
    data-bs-target="#navScroll"
  >
    <nav
      id="navScroll"
      class="navbar navbar-dark bg-black fixed-top px-vw-5"
      tabindex="0"
    >
      <div class="container">
        <a
          class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center"
          href="{% url 'main' %}"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            fill="currentColor"
            class="bi bi-stack"
            viewBox="0 0 16 16"
          >
            <path
              d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"
            />
            <path
              d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"
            />
          </svg>
          <span class="ms-md-1 mt-1 fw-bolder me-md-5"
            ><strong>BTS</strong></span
          >
        </a>

        <ul
          class="navbar-nav mx-auto mb-2 mb-lg-0 list-group list-group-horizontal"
        >
          <li class="nav-item">
            <a
              class="nav-link fs-5"
              href="/"
              aria-label="Homepage"
            >
              Home
            </a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link fs-5"
              href="/board"
              aria-label="A sample content page"
            >
              게시판
            </a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
            <a
              class="nav-link fs-5"
              href="{% url 'users:mypage' %}"
              aria-label="A system message page"
              >마이페이지</a
            >
            {% endif %}
          </li>
        </ul>
        {% if user.is_authenticated %}
        <a
          href="{% url 'users:logout' %}"
          aria-label="Download this template"
          class="btn btn-outline-light"
        >
          <small> {{ user.username }}님 로그아웃 </small>
        </a>
        {% else %}
        <a
          href="/users/login"
          aria-label="Download this template"
          class="btn btn-outline-light"
        >
          <small> Login </small>
        </a>
        {% endif %}
      </div>
    </nav>

    <div
      class="container-fluid px-vw-5 position-relative aos-init aos-animate"
      data-aos="fade"
    >
      <div class="position-absolute w-100 h-50 bg-black top-0 start-0"></div>
      <div
        class="position-relative py-vh-5 bg-cover bg-center rounded-5"
      >
        <div class="container bg-black px-vw-5 py-vh-3 rounded-5 shadow">
          <div class="row d-flex align-items-center">
            <div
              class="col-6 d-flex align-items-center bg-dark shadow rounded-5 p-0 aos-init aos-animate"
              data-aos="zoom-in-up"
            >
              <div class="row d-flex justify-content-center">
                <div class="col-12">
                  <img
                    src="../../static/img/webp/profile.webp"
                    width="800"
                    height="457"
                    alt="our CEO with some nice numbers"
                    class="img-fluid rounded-5"
                    loading="lazy"
                  />
                </div>
                <div class="col-12 col-lg-10 col-xl-8 text-center my-5">
                  <p
                    class="text-secondary text-center"
                    style="font-size: 8rem; line-height: 0.3em"
                  >
                    <strong> {{user.username}} </strong>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-5 offset-1">
              <style type="text/css">
                a:link {
                  color: white;
                  text-decoration: none;
                }
                a:visited {
                  color: white;
                  text-decoration: none;
                }
                a:hover {
                  color: orange;
                  text-decoration: none;
                }
              </style>
              <a href="{% url 'users:update' %}">
                <h2
                  class="display-huge fw-bolder aos-init aos-animate"
                  data-aos="zoom-in-left"
                  style='font-size:3.8rem;'
                >
                  회원정보수정
                </h2></a
              >

              <a href="{% url 'result:result_list' %}">
                <h2
                  class="display-huge fw-bolder border-top border-secondary pt-5 mt-5 aos-init aos-animate"
                  data-aos="zoom-in-left"
                  style='font-size:3.8rem;'
                >
                  지난악보보기
                </h2></a
              >

              <a href="{% url 'home:question_list' %}">
                <h2
                  class="display-huge fw-bolder border-top border-secondary pt-5 mt-5 aos-init aos-animate"
                  data-aos="zoom-in-left"
                  style='font-size:3.8rem;'
                >
                  내가쓴글보기
                </h2>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="../../static/js/bootstrap.bundle.min.js"></script>
    <script src="../../static/js/aos.js"></script>
    <script>
      AOS.init({
        duration: 800, // values from 0 to 3000, with step 50ms
      });
    </script>
    <script>
      let scrollpos = window.scrollY;
      const header = document.querySelector(".navbar");
      const header_height = header.offsetHeight;

      const add_class_on_scroll = () =>
        header.classList.add("scrolled", "shadow-sm");
      const remove_class_on_scroll = () =>
        header.classList.remove("scrolled", "shadow-sm");

      window.addEventListener("scroll", function () {
        scrollpos = window.scrollY;

        if (scrollpos >= header_height) {
          add_class_on_scroll();
        } else {
          remove_class_on_scroll();
        }

        console.log(scrollpos);
      });
    </script>
  </body>
</html>

Front/bigproject/users/templates/users/profile_real.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <title>Document</title>
</head>
<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">

    <nav id="navScroll" class="navbar navbar-dark bg-black fixed-top px-vw-5" tabindex="0">
      <div class="container">
        <a class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center" href="{% url 'main' %}">
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-stack" viewBox="0 0 16 16">
        <path d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"/>
        <path d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"/>
      </svg>
      <span class="ms-md-1 mt-1 fw-bolder me-md-5"><strong>BTS</strong></span>
    </a>
    
          <ul class="navbar-nav mx-auto mb-2 mb-lg-0 list-group list-group-horizontal">
          <li class="nav-item">
      <a class="nav-link fs-5" href="{% url 'main' %}" aria-label="Homepage">
        Home
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link fs-5" href="{% url 'home:question_list' %}" aria-label="A sample content page">
        게시판
      </a>
    </li>
    <li class="nav-item">
      {% if user.is_authenticated %}
      <a class="nav-link fs-5" href="{% url 'users:mypage' %}" aria-label="A system message page">마이페이지</a>
      {% endif %}
    </li>
    
        </ul>
          {% if user.is_authenticated %}
          <a href="{% url 'users:logout' %}" aria-label="Download this template" class="btn btn-outline-light">
            <small> {{ user.username }}님 로그아웃 </small>
          </a>
          {% else %}
          <a href="/users/login" aria-label="Download this template" class="btn btn-outline-light">
            <small> Login </small>
          </a>
          {% endif %}
    </div>
    </nav>
    
    <body class="bg-withe text-black mt-0" data-bs-spy="scroll" data-bs-target="#navScroll"><br><br><br><br><br><br>
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img"
                    src="https://blog.kakaocdn.net/dn/bftRiB/btqAjaghSBk/5CcN9W5qyCU8HLylVYcXb1/img.png">
                <div class="media-body">
                    <h2 class="account-heading">{{user.username}}</h2>
                    <p class="text-secondary">{{user.email}}</p>
                    <a href="{% url 'users:update' %}" style="color:white">개인정보수정</a>
                    <a href="#" style="color:white">지난 악보조회</a>
                    <a href="#" style="color:white">결제내역/알림</a>
                </div>
            </div>
        </div>
        <aside id="aside">
            <p>사이브다</p>
        </aside>
        </body>
    </html>

Front/bigproject/users/templates/users/update.html
{% load bootstrap4 %} {% load static %}
<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,shrink-to-fit=no"
    />
    <meta
      name="description"
      content="A well made and handcrafted Bootstrap 5 template"
    />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="img/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/favicon-16x16.png"
    />
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png" />
    <meta name="author" content="Holger Koenemann" />
    <meta name="generator" content="Eleventy v2.0.0" />
    <meta name="HandheldFriendly" content="true" />
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
      .box {
          margin: 0 auto;
          padding: 0;
          width: 886px;
          height: 753px;
          background: linear-gradient(45deg, #3366ff, #ff3399);
      }
  </style>
  </head>

  <body
    class="d-flex h-100 w-100 bg-black text-white"
    data-bs-spy="scroll"
    data-bs-target="#navScroll"
  >
    <div class="h-100 container-fluid">
      <div class="h-100 row d-flex align-items-stretch">
        <div
          class="col-12 col-md-7 col-lg-6 col-xl-5 d-flex align-items-start flex-column px-vw-5"
        >
          <header class="mb-auto py-vh-2 col-12">
            <a
              class="navbar-brand pe-md-4 fs-4 col-12 col-md-auto text-center"
              href="../../"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                fill="currentColor"
                class="bi bi-stack"
                viewBox="0 0 16 16"
              >
                <path
                  d="m14.12 10.163 1.715.858c.22.11.22.424 0 .534L8.267 15.34a.598.598 0 0 1-.534 0L.165 11.555a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.66zM7.733.063a.598.598 0 0 1 .534 0l7.568 3.784a.3.3 0 0 1 0 .535L8.267 8.165a.598.598 0 0 1-.534 0L.165 4.382a.299.299 0 0 1 0-.535L7.733.063z"
                />
                <path
                  d="m14.12 6.576 1.715.858c.22.11.22.424 0 .534l-7.568 3.784a.598.598 0 0 1-.534 0L.165 7.968a.299.299 0 0 1 0-.534l1.716-.858 5.317 2.659c.505.252 1.1.252 1.604 0l5.317-2.659z"
                />
              </svg>
              <span class="ms-md-1 mt-1 fw-bolder me-md-5">BTS</span>
            </a>
          </header>
          <main class="mb-auto col-12">
            <h1>회원정보</h1>
            <br>
            <form class="row" method="post">
              {% csrf_token %}{% bootstrap_form user_change_form %}
              <br>
              <div class="col-12">
                <br />

                <button type="submit" class="btn btn-white btn-xl mb-4">
                  제출</button
                ><br />
                <a
                  href="{% url 'users:delete' %}"
                  style="color: red"
                  class="btn btn-online-danger"
                  >회원탈퇴</a
                >
                <a
                  href="{% url 'users:change_password' %}"
                  style="color: white"
                  class="btn btn-online-danger"
                  >비밀번호 변경</a
                >
              </div>
            </form>
          </main>
        </div>

        <div class="box"></div>
      </div>
    </div>
  </body>
</html>