Front/bigproject/bigproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from home.views import hello
from django.conf import settings
from django.conf.urls.static import static

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="main"),
    path('users/', include('users.urls')),
    path('hello',hello, name="hello"),
    path('board/', include('home.urls'), name='home'),
    path('signup/', include('signup.urls')),
    path('upload/', upload, name='upload'),
    path('result/', include('result.urls'), name="result"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Front/bigproject/home/urls.py
from django.urls import path
from .views import *
from . import views

app_name = "home" # 앱 이름 설정
urlpatterns = [
    path('go_hello/', hello, name="hello"),
    path('', question_list, name="question_list"),
    path('<int:question_id>/', question_detail, name="question_detail"),
    path('answer/create/<int:question_id>/', answer_create, name="answer_create"),
    path('question_create/', question_create, name="question_create"),
    path('<int:pk>/edit/', question_edit, name='question_edit'),
    path('<int:pk>/delete/', question_delete, name='question_delete'),
    path('<int:pk>/answer/delete/', answer_delete, name='answer_delete'),
    path('search/', search, name="search"),
]

Front/bigproject/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200, null = False) 
    content = models.TextField() 
    create_date = models.DateTimeField(auto_now = True)
    imgfile = models.ImageField(null=True, upload_to="images", blank=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    updated_at = models.DateTimeField(auto_now=True)
  
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True)
    
class Sheet(models.Model):
    questions = models.ForeignKey(Question, on_delete=models.CASCADE)
    imgfile = models.ImageField()

Front/bigproject/home/forms.py
from django import forms
from home.models import Question, Answer, Sheet

class QuestionForm(forms.ModelForm): # 모델 폼을 상속받은 QuestionForm 클래스
  class Meta: # 내부 Meta 클래스
    model = Question
    fields = ['subject', 'content', 'imgfile']
    # labels 코드 추가하기
    labels = {
      'subject' : '제목',
      'content' : '내용',
      'imgfile' : '첨부파일',
    }
    
class AnswerForm(forms.ModelForm): # 모델 폼을 상속받은 QuestionForm 클래스
  class Meta: # 내부 Meta 클래스
    model = Answer
    fields = ['content']
    # labels 코드 추가하기
    labels = {
      'content' : '내용',
    }
    
class SheetForm(forms.ModelForm): # 모델 폼을 상속받은 QuestionForm 클래스
  class Meta: # 내부 Meta 클래스
    model = Sheet
    fields = ['imgfile']
    # labels 코드 추가하기
    labels = {
      'imgfile' : '첨부파일',
    }

Front/bigproject/home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import QuestionForm, AnswerForm
from django.core.paginator import Paginator
from django.contrib import messages
from django.db.models import Q


# Create your views here.
def hello(request):
    return render(request, 'home/hello.html')

def question_list(request):
  questions = Question.objects.order_by('-create_date') # Question 모델 데이터를 작성일시의 역순(-)으로 정렬한다.
  # Paging 기능 구현하기
  page = request.GET.get('page', '1') # GET 방식 요청 URL에서 page값을 가져올 때 사용(?page=1). page 파라미터가 없는 URL을 위해 기본값으로 1을 지정한 것
  paginator = Paginator(questions, 5) # Paginator 클래스는 questions를 페이징 객체 paginator로 변환. 페이지당 5개씩 보여주기
  page_obj = paginator.get_page(page) # page_obj 객체에는 여러 속성이 존재
  context = { 'questions_list' : page_obj } # page_obj를 question_list에 저장한다.
  return render(request, 'home/question_list.html', context)

def question_detail(request, question_id):
  # question = Question.objects.get(id=question_id) # urls에 mapping된 question_id와 같은 것
  question = get_object_or_404(Question, pk=question_id) # 404페이지 출력하기
  context = { 'a_question' : question} # 위의 question를 context 변수인 a_question에 저장한다.
  return render(request, 'home/question_detail.html', context)

 
# def answer_create(request, question_id):
#   if request.user.is_anonymous:
#     return redirect('users:login')
#   else:
#     a_question = get_object_or_404(Question, pk=question_id) # 어떤 question 글에 달린 answer?
#     a_content = request.POST.get('content') # 뒤에 content는 html>name이랑 같다
#     if a_content:
#       Answer.objects.create(question = a_question, content = a_content, user = request.user) # models.py = views.py
#       return redirect('home:question_detail', question_id=a_question.id)
#     else:
#       messages.warning(request, "답변을 입력해주세요.")
#       return redirect('home:question_detail', question_id=a_question.id)

def answer_create(request, question_id):
  if request.user.is_anonymous:
    return redirect('users:login')
  else:
    a_question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
      a_form = AnswerForm(request.POST)
      if a_form.is_valid():
        answer = a_form.save(commit=False) # 폼에 없는 필드인 create_date부분을 자동입력으로 모델을 설정하였기 때문에 a_form.save()라고 작성하여도 오류가 발생하지는 않는다.
        answer.user = request.user
        answer.question = a_question
        answer.save()
        return redirect('home:question_detail', question_id=a_question.id)
      else:
        messages.warning(request, "답변을 입력해주세요.")
        return redirect('home:question_detail', question_id=a_question.id)
    else: # request.method == 'GET'인 경우
      a_form = AnswerForm(request.GET) # QuestionForm 클래스로 생성한 객체 a_form을 사용할 것이다.
    context = {'form' : a_form }
    return render(request, 'home/question_detail.html', context)


def question_create(request):
  if request.user.is_anonymous:
    return redirect('users:login')
  else:
    if request.method == 'POST':
      a_form = QuestionForm(request.POST)
      if a_form.is_valid():
        question = a_form.save(commit=False) # 폼에 없는 필드인 create_date부분을 자동입력으로 모델을 설정하였기 때문에 a_form.save()라고 작성하여도 오류가 발생하지는 않는다.
        question.user = request.user
        question.save()
        files = request.FILES.getlist('imgfile')
        for a in files:
          print(1)
          sheet = Sheet()
          sheet.questions = question
          sheet.imgfile = a
          sheet.save()
        return redirect('home:question_list')
    else: # request.method == 'GET'인 경우
      a_form = QuestionForm() # QuestionForm 클래스로 생성한 객체 a_form을 사용할 것이다.
    context = {'form' : a_form }
    return render(request, 'home/question_form.html', context)
  
def question_edit(request, pk):
  question = Question.objects.get(id=pk)
  if request.method == "POST":
    if(question.user == request.user or request.user.is_staff == True):
      form = QuestionForm(request.POST, instance=question)
      if form.is_valid():
        question = form.save(commit = False)
        question.save()
        if request.FILES:
          print(1)
          sheet = Sheet.objects.filter(questions_id=pk)
          sheet.delete()
          files = request.FILES.getlist('imgfile')
          for a in files:
            sheet = Sheet()
            sheet.questions = question
            sheet.imgfile = a
            sheet.save()
        return redirect('home:question_detail', question_id=question.id)
  else:
    question = Question.objects.get(id=pk)
    if question.user == request.user or request.user.is_staff == True:
      form = QuestionForm(instance=question)
      context = {
          'form': form,
          'edit': '수정하기',
        }
      return render(request, "home/question_form.html", context)
    else:
      return redirect('home:question_detail', question_id=question.id)
    
    
def question_delete(request, pk):
  question = Question.objects.get(id=pk)
  if question.user == request.user or request.user.is_staff == True:
    question.delete()
    return redirect('home:question_list')
  else:
    return redirect('home:question_detail', question_id=question.id)
  
def answer_delete(request, pk):
  answer = Answer.objects.get(id=pk)
  if answer.user == request.user or request.user.is_staff == True:
    answer.delete()
    return redirect('home:question_detail', question_id=answer.question_id)
  else:
    return redirect('home:question_detail', question_id=answer.question_id)
  
  
def search(request):
  post = Question.objects.all().order_by('-id')
  search_type = request.GET.get('search_type', '')
  post = post.order_by('-create_date')
  q = request.GET.get('q', "") 

  if q:
    if len(q) > 1 :
      if search_type == 'all':
        post_list = post.filter( Q(subject__icontains=q) | Q(content__icontains=q) | Q(user__username__icontains=q))
      elif search_type == 'subject_content':
        post_list = post.filter( Q(subject__icontains=q) | Q(content__icontains=q))
      elif search_type == 'subject':
        post_list = post.filter(subject__icontains=q)    
      elif search_type == 'content':
        post_list = post.filter(content__icontains=q)    
      elif search_type == 'writer':
        post_list = post.filter(user__username__icontains=q)
      post_list = post_list.order_by('-create_date')
      page = request.GET.get('page', '1')
      paginator = Paginator(post_list, 5) # Paginator 클래스는 questions를 페이징 객체 paginator로 변환. 페이지당 5개씩 보여주기
      page_obj = paginator.get_page(page) # page_obj 객체에는 여러 속성이 존재
      context = { 'post' : page_obj, 'q' : q, 'search_type' : search_type }
      return render(request, 'home/question_list.html', context)
    
    else:
      messages.error(request, '검색어는 2글자 이상 입력해주세요.')
      return redirect('home:question_list')
    
  else:
    messages.warning(request, "검색어를 입력해주세요.")
    return redirect('home:question_list')

Front/bigproject/home/templates/home/hello.html
<h1>hello앱 안에 hello.html이야</h1>

Front/bigproject/home/templates/home/question_detail.html
{% extends 'base.html' %} 
{% load home_filter %} 
{% block content %}

<div class="container my-3">
  <h1 class="border-bottom py-2">{{ a_question.subject }}</h1>
  <div class="card my-3">
    <div class="card-body">
      <div
        class="card-text"
        style="color: black; font-size: 1.5em"
        font-sizes="16pt"
      >
        <br />
        {{ a_question.content }}
        <br />
        <div class="image-box">
          {% for sheet in a_question.sheet_set.all %}
          <img src="{{ sheet.imgfile.url }}" width="300" height="300" />
          {% endfor %}
        </div>
      </div>
      <div class="container my-3">
        <div class="badge-light py-2" style="color: black; text-align: right">
          {{ a_question.create_date }}<br />
          작성자 : {{ a_question.user }}
        </div>
      </div>
    </div>
  </div>
  <div>
    {% if request.user == a_question.user or request.user.is_staff == True %}
    <button
      aria-label="Download this template"
      class="btn btn-outline-dark"
      onclick="location.href='/board/{{ a_question.id }}/edit/'"
    >
      수정
    </button>
    <button
      aria-label="Download this template"
      class="btn btn-outline-danger"
      style="color: red"
      onclick='if(confirm("삭제하시겠습니까?") == true){delete_modal()}'
    >
      삭제
    </button>
    {% endif %}
  </div>
  <script type="text/javascript">
    function delete_modal() {
      location.replace("/board/{{ a_question.id }}/delete/");
    }
    function delete_modal1() {
      location.replace("/board/{{ a_question.answer_set }}/answer/delete/");
    }
  </script>
  <div class="border-bottom my-3 py-2">
    {{ a_question.answer_set.count }}개의 답변이 있습니다. 
    {% for answer in a_question.answer_set.all %}
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="color: black; font-size: 1.5em">
          {{ answer.content }}
        </div>
        <div class="d-flex justify-content-end">
          <div class="container my-3" style="color: black; text-align: right">
            {{ answer.create_date }}<br />
            작성자 : {{ answer.user }}
            <script type="text/javascript">
              function delete_modal1() {
                location.replace("/board/{{ answer.id }}/answer/delete/");
              }
            </script>
            {% if request.user == answer.user or request.user.is_staff == True %}
            <button
              aria-label="Download this template"
              class="btn btn-outline-danger"
              style="color: red"
              onclick='if(confirm("삭제하시겠습니까?") == true){delete_modal1()}'
            >
              삭제
            </button>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <form
      action="{% url 'home:answer_create' a_question.id %}"
      method="post"
      class="my-3"
    >
      {% csrf_token %} {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %} {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }} {% endif %} {% endfor %}
      </div>
      {% endif %}
      <!-- 오류표시 End -->
      {% for message in messages %} {{ message.tag }} {{ message }} {% endfor %}
      <div class="form-group">
        <textarea
          name="content"
          id="content"
          class="form-control"
          rows="10"
        ></textarea>
      </div>
      <input
        type="submit"
        value="답변등록"
        aria-label="Download this template"
        class="btn btn-outline-dark"
      />
      <!-- {{ form.as_p }}대신 forms.py 사용 -->
      <!-- 오류표시 Start -->
    </form>
  </div>
</div>
{% endblock %}

Front/bigproject/home/templates/home/question_form.html
{% extends 'base.html' %} 
{% load home_filter %} 
{% block content %}

<div>
  <div class="container">
    <h5>질문 등록</h5>
  </div>
  <form method="POST">
    {% csrf_token %}

    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %} 
      {% if field.errors %}
        <strong>{{ field.label }}</strong>
      {{ field.errors }} 
      {% endif %} 
      {% endfor %}
    </div>
    {% endif %}
    <script>
      let idNum = 0;
      function deepCopy() {
          const fileModule = document.getElementById('file-module-'+idNum);
  
          const newNode = fileModule.cloneNode(true);
  
          console.log(newNode)
  
          idNum++;
          newNode.id = 'file-module-' + idNum;
  
          fileModule.after(newNode);
      }
  </script>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
  
      <!-- 오류표시 Start -->
      {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}
      <!-- 오류표시 End -->
      <div class="container">
        <div class="form-group">
          <label for="subject">제목</label>
          <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
          <label for="content">내용</label>
          <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <span id='file-module-0'>
        <div class="form-group">
          <fieldset>
          <label for="imgfile">파일 첨부</label>
          <input type="file" id="imgfile" name="imgfile" class="btn btn-outline-dark">
          </fieldset>
        </div>
        </span>
        <button onclick="deepCopy()" type="button" class="btn btn-outline-dark">파일 추가</button>
        <br>
      <!-- {{ form.as_p }} -->
        <button class="btn btn-outline-warning">저장하기</button>
      </div>
  </form>
</div>

{% endblock %}

Front/bigproject/home/templates/home/question_list2.html
<!-- question_list.html -->

{% extends 'base.html' %}
{% load home_filter %}
{% block content %}
<style>
  table, th, td {
    
    
  }
  table {
    width: 1000px;
    height: 400px;
  }
  th {
    border-bottom: 1px solid #bcbcbc;
  }
  td {
    border-bottom:1px solid #FFFFFF;
    text-align: center;
  }
</style>

<div class="container my-3">
  <h1 class="border-bottom py-2">질문 리스트 보기</h1>
  <table class="table">
    <thead>
      <tr class="thead-dark">
        <th style="width:70px">번호</th>
        <th style="width:400px">제목</th>
        <th style="width:250px">작성일시</th>
        <th style="width:150px">작성자</th>
        <th style="width:70px">댓글 수</th>
      </tr>
    </thead>
    <tbody>
      {% if questions_list %}
      {% for question in questions_list %}
      <tr>
        <td>{{ questions_list.paginator.count|sub:questions_list.start_index|sub:forloop.counter0|add:1 }}</td>
        <td>
          <a href="{% url 'home:question_detail' question.id %}" style="color:white">{{ question.subject }}</a>
        </td>
        <td>{{ question.create_date }}</td>
        <td>{{ question.user }}</td>
        <td>
            {% if question.answer_set.count > 0%}
            {{ question.answer_set.count }}
            {% endif %}
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
      {% endif %}
    </tbody>
  </table>
  <ul>
    <!-- 이전 페이지가 있으면 -->
    {% if questions_list.has_previous %}
    <a href="?page={{ questions_list.previous_page_number }}" style="color:white">이전</a>
    {% endif %}
    <!-- 페이지 리스트 -->
    {% for page_number in questions_list.paginator.page_range %}
    <!-- 코드 추가하기 : 페이지 표시 제한 기능 구현하기 -->
    {% if questions_list.number|add:5 >= page_number and page_number >= questions_list.number|add:-5 %}
    <!-- 현재 페이지 번호랑 같다면 style을 다르게 줄 수 있다. -->
    {% if page_number == question_list.number %}
    <li>
      <a href="?page={{ page_number }}" style="color:skyblue">{{ page_number }}</a>
    </li>
    {% else %}
    <li>
      <a href="?page={{ page_number }}" style="color:white">{{ page_number }}</a>
    </li>
    {% endif %}
    {% endif %}
    {% endfor%}
    <!-- 다음 페이지가 있으면 -->
    {% if questions_list.has_next %}
    <a href="?page={{ questions_list.next_page_number }}" style="color:white">다음</a>
    {% endif %}
  </ul>
  <a href="{% url 'home:question_create' %}" style="color:white">질문 등록하기</a>
  <!-- 모델 폼 이용하지 않을 경우 -->
  {% comment %} <a href="{% url 'home:question_new' %}">질문 등록하기</a> {% endcomment %}
</div>


{% endblock %}

Front/bigproject/home/templates/home/search.html
{% extends 'base.html' %} {% load home_filter %} {% block content %}

<div id="board-search">
  <div class="container">
    <div class="search-window">
      <form action="{% url 'home:search' %}" method="get">
        >
        <div class="search-wrap">
          <label for="search" class="blind">공지사항 내용 검색</label>
          <input
            id="search"
            type="search"
            placeholder="Search"
            aria-label="Search"
            name="q"
            value="{{ q }}"
            placeholder="검색어를 입력해주세요."
            class="form-control- form-control-lg bg-white-800 border-white"
          />
          <button type="submit" class="btn btn-dark">검색</button>
          {% for message in messages %} {{ message.tag }} {{ message }} {%
          endfor %}
        </div>
      </form>
    </div>
  </div>
</div>

{% if not post %}
<h2>{{ q }}에 대한 검색 결과가 없습니다</h2>
{% else %}
<h2>{{ q }}에 대한 검색 결과</h2>
<table class="board-list">
  <thead>
    <tr class="thead-white">
      <th scope="col" class="th-num" height="70">번호</th>
      <th scope="col" class="th-title" height="70">제목</th>
      <th scope="col" class="th-date" height="70">작성일시</th>
      <th scope="col" class="th-title" height="70">작성자</th>
      <th scope="col" class="th-num" height="70">댓글 수</th>
    </tr>
  </thead>
  <tbody>
    {% if post %} {% for posts in post %}
    <tr>
      <td height="70">
        {{ post.paginator.count|sub:post.start_index|sub:forloop.counter0|add:1
        }}
      </td>
      <td>
        <a href="{% url 'home:question_detail' posts.id %}" style="color: black"
          >{{ posts.subject }}</a
        >
      </td>
      <td>{{ posts.create_date }}</td>
      <td>{{ posts.user }}</td>
      <td>
        {% if posts.answer_set.count > 0 %} {{ posts.answer_set.count }} {% else
        %} 0 {% endif %}
      </td>
    </tr>
    {% endfor %} {% else %}
    <tr>
      <td colspan="3">글이 없습니다.</td>
    </tr>
    {% endif %}
  </tbody>
</table>
{% endif %}
<ul>
  <li>
    <!-- 이전 페이지가 있으면 -->
    {% if post.has_previous %}
    <a
      href="?q={{ q }}&page={{ post.previous_page_number }}"
      style="color: black"
      class="btn btn-outline-danger"
      >이전</a
    >
    {% endif %}
    <!-- 페이지 리스트 -->
    {% for page_number in post.paginator.page_range %}
    <!-- 코드 추가하기 : 페이지 표시 제한 기능 구현하기 -->
    {% if post.number|add:5 >= page_number and page_number >= post.number|add:-5
    %}
    <!-- 현재 페이지 번호랑 같다면 style을 다르게 줄 수 있다. -->
    {% if page_number == post.number %}
    <a
      href="?page={{ page_number }}&q={{ q }}"
      style="color: skyblue"
      class="btn btn-outline-warning"
      >{{ page_number }}</a
    >
    {% else %}
    <a
      href="?page={{ page_number }}&q={{ q }}"
      style="color: black"
      class="btn btn-outline-dark"
      >{{ page_number }}</a
    >
    {% endif %} {% endif %} {% endfor%}
    <!-- 다음 페이지가 있으면 -->
    {% if post.has_next %}
    <a
      href="?q={{ q }}&page={{ post.next_page_number }}"
      style="color: black"
      class="btn btn-outline-warning"
      >다음</a
    >
    {% endif %}
  </li>
</ul>

{% endblock %}